services:
  ollama:
    # https://hub.docker.com/r/ollama/ollama
    # image: ollama/ollama:0.7.0
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    # image: ghcr.io/open-webui/open-webui:0.6.10
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: always
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "3001:8080"
    volumes:
      - ./open-webui:/app/backend/data
